#! /usr/bin/env bash

PREREQ=$(basename "$0")

has() {
    local tool=$1
    if [[ ! -z $(type -p "${tool}") ]]; then
        echo "${tool} installed."
        return 0
    else
        echo "WARNING: ${tool} not found."
        prereqs_found=false
        return 1
    fi
}

prereqs_check() {
    local config_file=${1:-prereqs.conf}
    prereqs_found=true
    set +e
    # shellcheck source=/dev/null
    . "${config_file}"
    set -e
    if [[ $prereqs_found == "true" ]]; then
        echo "OK: all prereqs found"
    else
        echo "ERROR: some prereqs missing, please install them"
        return 1
    fi
}

prereqs_update() {
    local tag=${1:-latest}
    if  ! has curl; then
        return 1
    fi
    echo "https://raw.githubusercontent.com/trussworks/prereqs/${tag}/prereqs"
    #     curl -O https://raw.githubusercontent.com/trussworks/prereqs/master/prereqs

}

prereqs_usage() {
    cat <<EOF
Usage: ${PREREQ} -c prereq.conf [-h] [-u [-t tag]]

       -c FILE    Load the config file
       -h         Print this help
       -u         Update prereq to current version from tag (default latest)
       -t         Tag to update to (default latest)
EOF
}

main() {
    # Enable the safeties
    set -eu -o pipefail
    local update_tag="latest"
    while getopts 'c:hut:' opt; do
        case ${opt} in
            c)
                prereqs_check "${OPTARG}"
                exit $?
                ;;
            h)
                prereqs_usage
                exit 0
                ;;
            u)
                prereqs_update "${update_tag}"
                exit $?
                ;;
            t)
                update_tag="${OPTARG}"
                ;;
            *)
                prereqs_usage
                exit 1
                ;;
        esac
    done
    prereqs_usage
    exit 1
}

# Execute main() if this is run in standalone mode (vs. from a unit test)
[ -z "${SHUNIT_VERSION}" ] && main "$@"
